### ISSUE TITLE
Python port of Niceware

### ISSUE THREAD

**Issue by moreati** [diracdeltas/niceware#10]
I've done a [Niceware for Python](https://github.com/moreati/python-niceware) port . Before I publicise it or upload it to PyPI do you have any objections/queries/changes you'd like me to address/fix?

I've included a test suite based closely on yours, and it passes. Phrases generated/converted by the Python port are interchangeable with phrases from your implementation. There's no command line interface yet, but that's my next priority. The code is Python 2.x and 3.x agnostic.

Stylistic changes include:
 - ``lowercase_with_underscores`` instead of ``camelCase``
 - ``bytes_to_passphrase()`` accepts any sequnce that `bytearray` can accept, rather than only accepting e.g. `bytes` objects.

**Comment by diracdeltas** [comment]
Nice! No objections here. Thanks for doing this.
