### ISSUE TITLE
niceware command in python-niceware

### ISSUE THREAD

**Issue by moreati** [diracdeltas/niceware#11]
I'm experimenting with adding a [command line interface to python-niceware](https://github.com/moreati/python-niceware/compare/command). e.g. 

```
$ python -m niceware
herein crestal chumping philoprogenitive frontal pressman vibrancy obnoxiety
$ python -m niceware --count 2 --length 5
gaoling rainmaking mutate spangling nonconvertible
slag simultaneously tazza intermediary sacrosanct
```

The current implementation also installs a script called `niceware`. I'm conscious that this encroaches on a global namespace. It might clash with any future CLI to your original implementation. Would you prefer I leave this script out of python-niceware, or change the name of the command, to e.g. `nicewarepy`?

**Comment by diracdeltas** [comment]
> The current implementation also installs a script called niceware

Not sure what you mean. In any case, I don't think many people are installing this module globally, so it shouldn't be an issue if you use the same name.

**Comment by moreati** [comment]
I mean that if this branch of python-nicewarewas was released onto PyPI, then (due to the `entry_point` in setup.py) `sudo pip install niceware` would create `/usr/bin/niceware`. If you intend to add a command interface to your implementation, then (as is) python-niceware's command would clash. You were here first though, you should get first first refusal on `/usr/bin/niceware`, if you want it.

Alternatively I might be overthinking all this, in which case I'll get on with it, and leave you in peace.

**Comment by diracdeltas** [comment]
ah i see. i am not planning on releasing a CLI (although someone else made https://www.npmjs.com/package/nicepass, which fortunately does not clash), so you can go for it. thanks for checking.
