### ISSUE TITLE
 Error: window.niceware is undefined

### ISSUE THREAD

**Issue by atoponce** [diracdeltas/niceware#35]
Running locally, when trying demo 2 to convert a hex to a nice phrase, or demo 3 to convert a phrase to hex, the following error is returned: `Error: window.niceware is undefined`. This is running in Firefox 80.0 on Debian unstable

**Comment by atoponce** [comment]
Chromium returns `Error: Cannot read property 'bytesToPassphrase' of undefined` for demo 2, and `Error: Cannot read property 'passphraseToBytes' of undefined` for demo 3.

**Comment by diracdeltas** [comment]
was the niceware script successfully included in your HTML? https://github.com/diracdeltas/niceware#usage-in-browser

does the remote site (https://diracdeltas.github.io/niceware/) work in your browser?

**Comment by atoponce** [comment]
> was the niceware script successfully included in your HTML? https://github.com/diracdeltas/niceware#usage-in-browser

I downloaded the latest ZIP released, and opened the index.html locally.  It appears Firefox is now blocking the `crossorigin=anonymous` attribute with "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/aaron/src/niceware/browser/niceware.js. (Reason: CORS request not http)." in the error.

> does the remote site (https://diracdeltas.github.io/niceware/) work in your browser?

Yes.

**Comment by diracdeltas** [comment]
@atoponce ah that makes sense. you probably need to run a localhost server in the demo folder for it to work instead of loading it from file://
