### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by frontsideair** [diracdeltas/niceware#4]
First of all, awesome tool!

But the demo page you provided may be used to generate passwords and it's not a good practice to do so. Even if it's only a static site, a good rule of thumb is avoid this altogether.

So I thought the page may show a notice saying it's only for demonstration purposes and one should never trust an online tool to generate passwords for them.

**Comment by diracdeltas** [comment]
Good idea, I had this thought originally but wasn't sure how to phrase it. Will give it another go.

**Comment by frontsideair** [comment]
Awesome!
