### ISSUE TITLE
Rust port of Niceware

### ISSUE THREAD

**Issue by healeycodes** [diracdeltas/niceware#44]
Thank you for writing this elegant library. I'm a big fan of it!

I ported it to Rust: https://github.com/healeycodes/niceware

It's pubished to crates.io https://crates.io/crates/niceware

It passes the same test suite as this library. Do let me know if you spot anything incorrect about this implementation. I've tried to make it a faithful port.

🦀

**Comment by diracdeltas** [comment]
@healeycodes thank you! this is awesome. please note that i just updated the wordlist to remove an offensive word, you probably want to do the same and mark it as a breaking change.
