### ISSUE TITLE
Offensive words

### ISSUE THREAD

**Issue by SeanLMcCullough** [diracdeltas/niceware#49]
There are some offensive / objectionable words in the wordlist.

Although some are not exclusively bad words, they do appear unprofessional in generated passwords...

<details>
  <summary>Words</summary>
- Dike
- Dildo
- Dildoe
- Prick
</details>

**Comment by diracdeltas** [comment]
there is this warning in the readme:

```WARNING: The wordlist has not been rigorously checked for offensive words. Use at your own risk.```

that said, i am happy to replace these words with other words that fit in the same spot lexicographically.

**Comment by SeanLMcCullough** [comment]
Thanks for the heads-up. And makes sense.

I would offer suggestions, but some of those are very hard to find alphabetically fitting replacements...

**Comment by offsetcyan** [comment]
Is there a reason they have to fit lexicographically, as opposed to simply being replaced with new words and the list re-sorted?

**Comment by sts10** [comment]
Before seeing this issue, I made an attempt at replacing some of these words in PR #52 . 

> I would offer suggestions, but some of those are very hard to find alphabetically fitting replacements...

Is that a requirement for changes to the word list? I assumed not. I guess we'll see by whether my PR is accepted or not.

**Comment by diracdeltas** [comment]
i was hoping to avoid re-sorting the list so that *most* people's passphrases would work after the version upgrade (or at least they could easily figure out which words needed to be swapped). but i'm not opposed to doing a larger breaking change at this point.

**Comment by sts10** [comment]
Ah, I hadn't thought of that. I admit I don't have a firm grasp of how making changes to this word list will affect users... if Niceware was just a passphrase generator, it'd won't really matter. But if Niceware is expected to maintain a static relation between a word and random 16-bits, I could see edits to the word list would be a more sensitive undertaking. 

I don't have an easy way of generating alphabetically fitting replacements for 400+ words, but it's something I could look into.

**Comment by diracdeltas** [comment]
no worries, i think we should just do a breaking change without worrying about keeping the order.
